#!/usr/bin/env python
# -*- coding: utf-8 -*-
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.ensemble import AdaBoostRegressor, RandomForestRegressor, GradientBoostingRegressor, AdaBoostClassifier
from sklearn.metrics import SCORERS
from TaxiFareModel.trainer import Trainer
from TaxiFareModel.data import get_data, clean_data
from sklearn.model_selection import train_test_split

lin_reg = LinearRegression()
ridge = Ridge()
las = Lasso()
rand_forest = RandomForestRegressor()
grad_boost = GradientBoostingRegressor()
ada_boost = AdaBoostRegressor()

compendium = {'linear_regression':lin_reg, 'ridge':ridge, 'lasso':las,
              'random_forest':rand_forest, 'gradient_boosting':grad_boost,
              'Ada_boosting':ada_boost}

for key, value in compendium.items():
    df = get_data(nrows=1_000)
    df_clean = clean_data(df)
    X = df_clean.drop(columns='fare_amount')
    y = df_clean['fare_amount']
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    trainer = Trainer(X_train, y_train)
    trainer.run(model_name=key, model=value)
    print(f"The score of {key} is {trainer.evaluate(X_test, y_test)}")

    # trainer.save_model("test_model")
